# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setStyleSheet("background-color: rgb(17, 19, 22);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Top_Bar = QtWidgets.QFrame(parent=self.centralwidget)
        self.Top_Bar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.Top_Bar.setStyleSheet("background-color:  rgb(35, 38, 53);")
        self.Top_Bar.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.Top_Bar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Top_Bar.setObjectName("Top_Bar")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Top_Bar)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_top = QtWidgets.QFrame(parent=self.Top_Bar)
        self.frame_top.setMinimumSize(QtCore.QSize(0, 70))
        self.frame_top.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_top.setObjectName("frame_top")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_top)
        self.label_3.setGeometry(QtCore.QRect(370, 10, 90, 16))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.frame_top)
        self.verticalLayout.addWidget(self.Top_Bar)
        self.Content = QtWidgets.QFrame(parent=self.centralwidget)
        self.Content.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.Content.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Content.setObjectName("Content")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Content)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_left_menu = QtWidgets.QFrame(parent=self.Content)
        self.frame_left_menu.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_left_menu.setMaximumSize(QtCore.QSize(70, 16777215))
        self.frame_left_menu.setStyleSheet("background-color: rgb(35, 38, 53)")
        self.frame_left_menu.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_left_menu.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_left_menu.setObjectName("frame_left_menu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_left_menu)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn_page_1 = QtWidgets.QPushButton(parent=self.frame_left_menu)
        self.btn_page_1.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_page_1.setStyleSheet("QPushButton {\n"
                                      "    color: rgb(255, 255, 255);\n"
                                      "    background-color: rgb(35, 38, 53);\n"
                                      "    border: 0px solid;\n"
                                      "}\n"
                                      "QPushButton:hover {\n"
                                      "    background-color: rgb(49, 54, 80);\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton:checked {\n"
                                      "    background-color: rgb(49, 54, 80);\n"
                                      "}")
        self.btn_page_1.setCheckable(True)
        self.btn_page_1.setChecked(True)
        self.btn_page_1.setAutoExclusive(True)
        self.btn_page_1.setObjectName("btn_page_1")
        self.verticalLayout_3.addWidget(self.btn_page_1)
        self.btn_page_2 = QtWidgets.QPushButton(parent=self.frame_left_menu)
        self.btn_page_2.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_page_2.setStyleSheet("QPushButton {\n"
                                      "    color: rgb(255, 255, 255);\n"
                                      "    background-color:  rgb(35, 38, 53);\n"
                                      "    border: 0px solid;\n"
                                      "}\n"
                                      "QPushButton:hover {\n"
                                      "    background-color: rgb(49, 54, 80);\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton:checked {\n"
                                      "    background-color: rgb(49, 54, 80);\n"
                                      "}")
        self.btn_page_2.setCheckable(True)
        self.btn_page_2.setChecked(False)
        self.btn_page_2.setAutoExclusive(True)
        self.btn_page_2.setObjectName("btn_page_2")
        self.verticalLayout_3.addWidget(self.btn_page_2)
        self.btn_page_3 = QtWidgets.QPushButton(parent=self.frame_left_menu)
        self.btn_page_3.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_page_3.setStyleSheet("QPushButton {\n"
                                      "    color: rgb(255, 255, 255);\n"
                                      "    background-color:  rgb(35, 38, 53);\n"
                                      "    border: 0px solid;\n"
                                      "}\n"
                                      "QPushButton:hover {\n"
                                      "    background-color: rgb(49, 54, 80);\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton:checked {\n"
                                      "    background-color: rgb(49, 54, 80);\n"
                                      "}")
        self.btn_page_3.setCheckable(True)
        self.btn_page_3.setAutoExclusive(True)
        self.btn_page_3.setObjectName("btn_page_3")
        self.verticalLayout_3.addWidget(self.btn_page_3)
        self.frame_top_menus = QtWidgets.QFrame(parent=self.frame_left_menu)
        self.frame_top_menus.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_top_menus.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_top_menus.setObjectName("frame_top_menus")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_top_menus)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3.addWidget(
            self.frame_top_menus, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.horizontalLayout_2.addWidget(self.frame_left_menu)
        self.frame_pages = QtWidgets.QFrame(parent=self.Content)
        self.frame_pages.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_pages.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_pages.setObjectName("frame_pages")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_pages)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.frame_pages)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_3 = QtWidgets.QFrame(parent=self.page_1)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.frame_3)
        self.pushButton_5.setGeometry(QtCore.QRect(390, 70, 113, 32))
        self.pushButton_5.setStyleSheet("QPushButton {\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    background-color: rgb(35, 38, 53);\n"
                                        "    border: 0px solid;\n"
                                        "}\n"
                                        "QPushButton:hover {\n"
                                        "    background-color: rgb(49, 54, 80);\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:checked {\n"
                                        "    background-color: rgb(49, 54, 80);\n"
                                        "}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.lineEdit_19 = QtWidgets.QLineEdit(parent=self.frame_3)
        self.lineEdit_19.setGeometry(QtCore.QRect(140, 70, 240, 30))
        self.lineEdit_19.setMinimumSize(QtCore.QSize(240, 30))
        self.lineEdit_19.setMaximumSize(QtCore.QSize(240, 30))
        self.lineEdit_19.setStyleSheet("QLineEdit {\n"
                                       "    border: 2px solid rgb(37,39,48);\n"
                                       "    border-radius: 50px;\n"
                                       "    color: #FFF;\n"
                                       "    padding-left: 20px;\n"
                                       "    padding-right: 20px;\n"
                                       "}")
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.progressBar = QtWidgets.QProgressBar(parent=self.frame_3)
        self.progressBar.setGeometry(QtCore.QRect(140, 120, 361, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_7.addWidget(self.frame_3)
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame = QtWidgets.QFrame(parent=self.page_2)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(80, 10, 240, 30))
        self.lineEdit.setMinimumSize(QtCore.QSize(240, 30))
        self.lineEdit.setMaximumSize(QtCore.QSize(240, 30))
        self.lineEdit.setStyleSheet("QLineEdit {\n"
                                    "    border: 2px solid rgb(37,39,48);\n"
                                    "    border-radius: 50px;\n"
                                    "    color: #FFF;\n"
                                    "    padding-left: 20px;\n"
                                    "    padding-right: 20px;\n"
                                    "}")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(330, 10, 240, 30))
        self.lineEdit_2.setMinimumSize(QtCore.QSize(240, 30))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(240, 30))
        self.lineEdit_2.setStyleSheet("QLineEdit {\n"
                                      "    border: 2px solid rgb(37,39,48);\n"
                                      "    border-radius: 50px;\n"
                                      "    color: #FFF;\n"
                                      "    padding-left: 20px;\n"
                                      "    padding-right: 20px;\n"
                                      "}")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_3.setGeometry(QtCore.QRect(80, 50, 240, 30))
        self.lineEdit_3.setMinimumSize(QtCore.QSize(240, 30))
        self.lineEdit_3.setMaximumSize(QtCore.QSize(240, 30))
        self.lineEdit_3.setStyleSheet("QLineEdit {\n"
                                      "    border: 2px solid rgb(37,39,48);\n"
                                      "    border-radius: 50px;\n"
                                      "    color: #FFF;\n"
                                      "    padding-left: 20px;\n"
                                      "    padding-right: 20px;\n"
                                      "}")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_4.setGeometry(QtCore.QRect(330, 50, 240, 30))
        self.lineEdit_4.setMinimumSize(QtCore.QSize(240, 30))
        self.lineEdit_4.setMaximumSize(QtCore.QSize(240, 30))
        self.lineEdit_4.setStyleSheet("QLineEdit {\n"
                                      "    border: 2px solid rgb(37,39,48);\n"
                                      "    border-radius: 50px;\n"
                                      "    color: #FFF;\n"
                                      "    padding-left: 20px;\n"
                                      "    padding-right: 20px;\n"
                                      "}")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_5.setGeometry(QtCore.QRect(80, 90, 240, 30))
        self.lineEdit_5.setMinimumSize(QtCore.QSize(240, 30))
        self.lineEdit_5.setMaximumSize(QtCore.QSize(240, 30))
        self.lineEdit_5.setStyleSheet("QLineEdit {\n"
                                      "    border: 2px solid rgb(37,39,48);\n"
                                      "    border-radius: 50px;\n"
                                      "    color: #FFF;\n"
                                      "    padding-left: 20px;\n"
                                      "    padding-right: 20px;\n"
                                      "}")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_6.setGeometry(QtCore.QRect(330, 90, 240, 30))
        self.lineEdit_6.setMinimumSize(QtCore.QSize(240, 30))
        self.lineEdit_6.setMaximumSize(QtCore.QSize(240, 30))
        self.lineEdit_6.setStyleSheet("QLineEdit {\n"
                                      "    border: 2px solid rgb(37,39,48);\n"
                                      "    border-radius: 50px;\n"
                                      "    color: #FFF;\n"
                                      "    padding-left: 20px;\n"
                                      "    padding-right: 20px;\n"
                                      "}")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.pushButton = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton.setGeometry(QtCore.QRect(260, 130, 113, 32))
        self.pushButton.setStyleSheet("QPushButton {\n"
                                      "    color: rgb(255, 255, 255);\n"
                                      "    background-color: rgb(35, 38, 53);\n"
                                      "    border: 0px solid;\n"
                                      "}\n"
                                      "QPushButton:hover {\n"
                                      "    background-color: rgb(49, 54, 80);\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton:checked {\n"
                                      "    background-color: rgb(49, 54, 80);\n"
                                      "}")
        self.pushButton.setObjectName("pushButton")
        self.listWidget = QtWidgets.QListWidget(parent=self.frame)
        self.listWidget.setGeometry(QtCore.QRect(35, 200, 591, 291))
        self.listWidget.setStyleSheet("background-color:  rgb(35, 38, 53);\n"
                                      "color:#FFF;")
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_6.addWidget(self.frame)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_2 = QtWidgets.QFrame(parent=self.page_3)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.lineEdit_13 = QtWidgets.QLineEdit(parent=self.frame_2)
        self.lineEdit_13.setGeometry(QtCore.QRect(80, 90, 240, 30))
        self.lineEdit_13.setMinimumSize(QtCore.QSize(240, 30))
        self.lineEdit_13.setMaximumSize(QtCore.QSize(240, 30))
        self.lineEdit_13.setStyleSheet("QLineEdit {\n"
                                       "    border: 2px solid rgb(37,39,48);\n"
                                       "    border-radius: 50px;\n"
                                       "    color: #FFF;\n"
                                       "    padding-left: 20px;\n"
                                       "    padding-right: 20px;\n"
                                       "}")
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_14 = QtWidgets.QLineEdit(parent=self.frame_2)
        self.lineEdit_14.setGeometry(QtCore.QRect(80, 50, 240, 30))
        self.lineEdit_14.setMinimumSize(QtCore.QSize(240, 30))
        self.lineEdit_14.setMaximumSize(QtCore.QSize(240, 30))
        self.lineEdit_14.setStyleSheet("QLineEdit {\n"
                                       "    border: 2px solid rgb(37,39,48);\n"
                                       "    border-radius: 50px;\n"
                                       "    color: #FFF;\n"
                                       "    padding-left: 20px;\n"
                                       "    padding-right: 20px;\n"
                                       "}")
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.lineEdit_15 = QtWidgets.QLineEdit(parent=self.frame_2)
        self.lineEdit_15.setGeometry(QtCore.QRect(330, 90, 240, 30))
        self.lineEdit_15.setMinimumSize(QtCore.QSize(240, 30))
        self.lineEdit_15.setMaximumSize(QtCore.QSize(240, 30))
        self.lineEdit_15.setStyleSheet("QLineEdit {\n"
                                       "    border: 2px solid rgb(37,39,48);\n"
                                       "    border-radius: 50px;\n"
                                       "    color: #FFF;\n"
                                       "    padding-left: 20px;\n"
                                       "    padding-right: 20px;\n"
                                       "}")
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.lineEdit_16 = QtWidgets.QLineEdit(parent=self.frame_2)
        self.lineEdit_16.setGeometry(QtCore.QRect(330, 50, 240, 30))
        self.lineEdit_16.setMinimumSize(QtCore.QSize(240, 30))
        self.lineEdit_16.setMaximumSize(QtCore.QSize(240, 30))
        self.lineEdit_16.setStyleSheet("QLineEdit {\n"
                                       "    border: 2px solid rgb(37,39,48);\n"
                                       "    border-radius: 50px;\n"
                                       "    color: #FFF;\n"
                                       "    padding-left: 20px;\n"
                                       "    padding-right: 20px;\n"
                                       "}")
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.lineEdit_17 = QtWidgets.QLineEdit(parent=self.frame_2)
        self.lineEdit_17.setGeometry(QtCore.QRect(330, 10, 240, 30))
        self.lineEdit_17.setMinimumSize(QtCore.QSize(240, 30))
        self.lineEdit_17.setMaximumSize(QtCore.QSize(240, 30))
        self.lineEdit_17.setStyleSheet("QLineEdit {\n"
                                       "    border: 2px solid rgb(37,39,48);\n"
                                       "    border-radius: 50px;\n"
                                       "    color: #FFF;\n"
                                       "    padding-left: 20px;\n"
                                       "    padding-right: 20px;\n"
                                       "}")
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_3.setGeometry(QtCore.QRect(200, 130, 113, 32))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    background-color: rgb(35, 38, 53);\n"
                                        "    border: 0px solid;\n"
                                        "}\n"
                                        "QPushButton:hover {\n"
                                        "    background-color: rgb(49, 54, 80);\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:checked {\n"
                                        "    background-color: rgb(49, 54, 80);\n"
                                        "}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.lineEdit_18 = QtWidgets.QLineEdit(parent=self.frame_2)
        self.lineEdit_18.setGeometry(QtCore.QRect(80, 10, 240, 30))
        self.lineEdit_18.setMinimumSize(QtCore.QSize(240, 30))
        self.lineEdit_18.setMaximumSize(QtCore.QSize(240, 30))
        self.lineEdit_18.setStyleSheet("QLineEdit {\n"
                                       "    border: 2px solid rgb(37,39,48);\n"
                                       "    border-radius: 50px;\n"
                                       "    color: #FFF;\n"
                                       "    padding-left: 20px;\n"
                                       "    padding-right: 20px;\n"
                                       "}")
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.listWidget_3 = QtWidgets.QListWidget(parent=self.frame_2)
        self.listWidget_3.setGeometry(QtCore.QRect(35, 200, 181, 291))
        self.listWidget_3.setStyleSheet("background-color:  rgb(35, 38, 53);\n"
                                        "color:#FFF;")
        self.listWidget_3.setObjectName("listWidget_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_4.setGeometry(QtCore.QRect(340, 130, 113, 32))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    background-color: rgb(35, 38, 53);\n"
                                        "    border: 0px solid;\n"
                                        "}\n"
                                        "QPushButton:hover {\n"
                                        "    background-color: rgb(49, 54, 80);\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:checked {\n"
                                        "    background-color: rgb(49, 54, 80);\n"
                                        "}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_8.addWidget(self.frame_2)
        self.stackedWidget.addWidget(self.page_3)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.horizontalLayout_2.addWidget(self.frame_pages)
        self.verticalLayout.addWidget(self.Content)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Twitter Keeper"))
        self.btn_page_1.setText(_translate("MainWindow", "Home"))
        self.btn_page_2.setText(_translate("MainWindow", "Search"))
        self.btn_page_3.setText(_translate("MainWindow", "Analyze"))
        self.pushButton_5.setText(_translate("MainWindow", "Pull Tweets"))
        self.lineEdit_19.setPlaceholderText(
            _translate("MainWindow", "Keyword"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Hashtag"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Author"))
        self.lineEdit_3.setPlaceholderText(
            _translate("MainWindow", "Location"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "Text"))
        self.lineEdit_5.setPlaceholderText(
            _translate("MainWindow", "Start Time"))
        self.lineEdit_6.setPlaceholderText(
            _translate("MainWindow", "End Time"))
        self.pushButton.setText(_translate("MainWindow", "Search"))
        self.lineEdit_13.setPlaceholderText(
            _translate("MainWindow", "Start Time"))
        self.lineEdit_14.setPlaceholderText(
            _translate("MainWindow", "Location"))
        self.lineEdit_15.setPlaceholderText(
            _translate("MainWindow", "End Time"))
        self.lineEdit_16.setPlaceholderText(_translate("MainWindow", "Text"))
        self.lineEdit_17.setPlaceholderText(_translate("MainWindow", "Author"))
        self.pushButton_3.setText(_translate("MainWindow", "Search"))
        self.lineEdit_18.setPlaceholderText(
            _translate("MainWindow", "Hashtag"))
        self.pushButton_4.setText(_translate("MainWindow", "Top Trend"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    # PAGE 1
    ui.btn_page_1.clicked.connect(
        lambda: ui.stackedWidget.setCurrentWidget(ui.page_1))

    # PAGE 2
    ui.btn_page_2.clicked.connect(
        lambda: ui.stackedWidget.setCurrentWidget(ui.page_2))

    # PAGE 3
    ui.btn_page_3.clicked.connect(
        lambda: ui.stackedWidget.setCurrentWidget(ui.page_3))
    MainWindow.show()
    sys.exit(app.exec())
