# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setStyleSheet("background-color: rgb(17, 19, 22);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Top_Bar = QtWidgets.QFrame(parent=self.centralwidget)
        self.Top_Bar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.Top_Bar.setStyleSheet("background-color:  rgb(35, 38, 53);")
        self.Top_Bar.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.Top_Bar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Top_Bar.setObjectName("Top_Bar")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Top_Bar)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_top = QtWidgets.QFrame(parent=self.Top_Bar)
        self.frame_top.setMinimumSize(QtCore.QSize(0, 70))
        self.frame_top.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_top.setObjectName("frame_top")
        self.Title = QtWidgets.QLabel(parent=self.frame_top)
        self.Title.setGeometry(QtCore.QRect(370, 10, 90, 16))
        self.Title.setStyleSheet("color: rgb(255, 255, 255);")
        self.Title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Title.setObjectName("Title")
        self.verticalLayout_2.addWidget(self.frame_top)
        self.verticalLayout.addWidget(self.Top_Bar)
        self.Content = QtWidgets.QFrame(parent=self.centralwidget)
        self.Content.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.Content.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Content.setObjectName("Content")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Content)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_left_menu = QtWidgets.QFrame(parent=self.Content)
        self.frame_left_menu.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_left_menu.setMaximumSize(QtCore.QSize(70, 16777215))
        self.frame_left_menu.setStyleSheet("background-color: rgb(35, 38, 53)")
        self.frame_left_menu.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_left_menu.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_left_menu.setObjectName("frame_left_menu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_left_menu)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Home_Page = QtWidgets.QPushButton(parent=self.frame_left_menu)
        self.Home_Page.setMinimumSize(QtCore.QSize(0, 40))
        self.Home_Page.setStyleSheet("QPushButton {\n"
                                     "    color: rgb(255, 255, 255);\n"
                                     "    background-color: rgb(35, 38, 53);\n"
                                     "    border: 0px solid;\n"
                                     "}\n"
                                     "QPushButton:hover {\n"
                                     "    background-color: rgb(49, 54, 80);\n"
                                     "}\n"
                                     "\n"
                                     "QPushButton:checked {\n"
                                     "    background-color: rgb(49, 54, 80);\n"
                                     "}")
        self.Home_Page.setCheckable(True)
        self.Home_Page.setChecked(True)
        self.Home_Page.setAutoExclusive(True)
        self.Home_Page.setObjectName("Home_Page")
        self.verticalLayout_3.addWidget(self.Home_Page)
        self.Search_Page = QtWidgets.QPushButton(parent=self.frame_left_menu)
        self.Search_Page.setMinimumSize(QtCore.QSize(0, 40))
        self.Search_Page.setStyleSheet("QPushButton {\n"
                                       "    color: rgb(255, 255, 255);\n"
                                       "    background-color:  rgb(35, 38, 53);\n"
                                       "    border: 0px solid;\n"
                                       "}\n"
                                       "QPushButton:hover {\n"
                                       "    background-color: rgb(49, 54, 80);\n"
                                       "}\n"
                                       "\n"
                                       "QPushButton:checked {\n"
                                       "    background-color: rgb(49, 54, 80);\n"
                                       "}")
        self.Search_Page.setCheckable(True)
        self.Search_Page.setChecked(False)
        self.Search_Page.setAutoExclusive(True)
        self.Search_Page.setObjectName("Search_Page")
        self.verticalLayout_3.addWidget(self.Search_Page)
        self.Analyze_Page = QtWidgets.QPushButton(parent=self.frame_left_menu)
        self.Analyze_Page.setMinimumSize(QtCore.QSize(0, 40))
        self.Analyze_Page.setStyleSheet("QPushButton {\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    background-color:  rgb(35, 38, 53);\n"
                                        "    border: 0px solid;\n"
                                        "}\n"
                                        "QPushButton:hover {\n"
                                        "    background-color: rgb(49, 54, 80);\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:checked {\n"
                                        "    background-color: rgb(49, 54, 80);\n"
                                        "}")
        self.Analyze_Page.setCheckable(True)
        self.Analyze_Page.setAutoExclusive(True)
        self.Analyze_Page.setObjectName("Analyze_Page")
        self.verticalLayout_3.addWidget(self.Analyze_Page)
        self.frame_top_menus = QtWidgets.QFrame(parent=self.frame_left_menu)
        self.frame_top_menus.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_top_menus.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_top_menus.setObjectName("frame_top_menus")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_top_menus)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3.addWidget(
            self.frame_top_menus, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.horizontalLayout_2.addWidget(self.frame_left_menu)
        self.frame_pages = QtWidgets.QFrame(parent=self.Content)
        self.frame_pages.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_pages.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_pages.setObjectName("frame_pages")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_pages)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.frame_pages)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_3 = QtWidgets.QFrame(parent=self.page_1)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.PullTweet_Field = QtWidgets.QPushButton(parent=self.frame_3)
        self.PullTweet_Field.setGeometry(QtCore.QRect(400, 110, 113, 32))
        self.PullTweet_Field.setStyleSheet("QPushButton {\n"
                                           "    color: rgb(255, 255, 255);\n"
                                           "    background-color: rgb(35, 38, 53);\n"
                                           "    border: 0px solid;\n"
                                           "}\n"
                                           "QPushButton:hover {\n"
                                           "    background-color: rgb(49, 54, 80);\n"
                                           "}\n"
                                           "\n"
                                           "QPushButton:checked {\n"
                                           "    background-color: rgb(49, 54, 80);\n"
                                           "}")
        self.PullTweet_Field.setObjectName("PullTweet_Field")
        self.Keyword_Pull_Field = QtWidgets.QLineEdit(parent=self.frame_3)
        self.Keyword_Pull_Field.setGeometry(QtCore.QRect(140, 70, 240, 30))
        self.Keyword_Pull_Field.setMinimumSize(QtCore.QSize(240, 30))
        self.Keyword_Pull_Field.setMaximumSize(QtCore.QSize(240, 30))
        self.Keyword_Pull_Field.setStyleSheet("QLineEdit {\n"
                                              "    border: 2px solid rgb(37,39,48);\n"
                                              "    border-radius: 50px;\n"
                                              "    color: #FFF;\n"
                                              "    padding-left: 20px;\n"
                                              "    padding-right: 20px;\n"
                                              "}")
        self.Keyword_Pull_Field.setObjectName("Keyword_Pull_Field")
        self.progressBar = QtWidgets.QProgressBar(parent=self.frame_3)
        self.progressBar.setGeometry(QtCore.QRect(140, 170, 361, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.Keyword_Pull_Field_2 = QtWidgets.QLineEdit(parent=self.frame_3)
        self.Keyword_Pull_Field_2.setGeometry(QtCore.QRect(140, 110, 240, 30))
        self.Keyword_Pull_Field_2.setMinimumSize(QtCore.QSize(240, 30))
        self.Keyword_Pull_Field_2.setMaximumSize(QtCore.QSize(240, 30))
        self.Keyword_Pull_Field_2.setStyleSheet("QLineEdit {\n"
                                                "    border: 2px solid rgb(37,39,48);\n"
                                                "    border-radius: 50px;\n"
                                                "    color: #FFF;\n"
                                                "    padding-left: 20px;\n"
                                                "    padding-right: 20px;\n"
                                                "}")
        self.Keyword_Pull_Field_2.setObjectName("Keyword_Pull_Field_2")
        self.verticalLayout_7.addWidget(self.frame_3)
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame = QtWidgets.QFrame(parent=self.page_2)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.Hashtag_Search = QtWidgets.QLineEdit(parent=self.frame)
        self.Hashtag_Search.setGeometry(QtCore.QRect(80, 10, 240, 30))
        self.Hashtag_Search.setMinimumSize(QtCore.QSize(240, 30))
        self.Hashtag_Search.setMaximumSize(QtCore.QSize(240, 30))
        self.Hashtag_Search.setStyleSheet("QLineEdit {\n"
                                          "    border: 2px solid rgb(37,39,48);\n"
                                          "    border-radius: 50px;\n"
                                          "    color: #FFF;\n"
                                          "    padding-left: 20px;\n"
                                          "    padding-right: 20px;\n"
                                          "}")
        self.Hashtag_Search.setObjectName("Hashtag_Search")
        self.Author_Search = QtWidgets.QLineEdit(parent=self.frame)
        self.Author_Search.setGeometry(QtCore.QRect(330, 10, 240, 30))
        self.Author_Search.setMinimumSize(QtCore.QSize(240, 30))
        self.Author_Search.setMaximumSize(QtCore.QSize(240, 30))
        self.Author_Search.setStyleSheet("QLineEdit {\n"
                                         "    border: 2px solid rgb(37,39,48);\n"
                                         "    border-radius: 50px;\n"
                                         "    color: #FFF;\n"
                                         "    padding-left: 20px;\n"
                                         "    padding-right: 20px;\n"
                                         "}")
        self.Author_Search.setObjectName("Author_Search")
        self.Location_Search = QtWidgets.QLineEdit(parent=self.frame)
        self.Location_Search.setGeometry(QtCore.QRect(80, 50, 240, 30))
        self.Location_Search.setMinimumSize(QtCore.QSize(240, 30))
        self.Location_Search.setMaximumSize(QtCore.QSize(240, 30))
        self.Location_Search.setStyleSheet("QLineEdit {\n"
                                           "    border: 2px solid rgb(37,39,48);\n"
                                           "    border-radius: 50px;\n"
                                           "    color: #FFF;\n"
                                           "    padding-left: 20px;\n"
                                           "    padding-right: 20px;\n"
                                           "}")
        self.Location_Search.setObjectName("Location_Search")
        self.Text_Search = QtWidgets.QLineEdit(parent=self.frame)
        self.Text_Search.setGeometry(QtCore.QRect(330, 50, 240, 30))
        self.Text_Search.setMinimumSize(QtCore.QSize(240, 30))
        self.Text_Search.setMaximumSize(QtCore.QSize(240, 30))
        self.Text_Search.setStyleSheet("QLineEdit {\n"
                                       "    border: 2px solid rgb(37,39,48);\n"
                                       "    border-radius: 50px;\n"
                                       "    color: #FFF;\n"
                                       "    padding-left: 20px;\n"
                                       "    padding-right: 20px;\n"
                                       "}")
        self.Text_Search.setObjectName("Text_Search")
        self.StartTime_Search = QtWidgets.QLineEdit(parent=self.frame)
        self.StartTime_Search.setGeometry(QtCore.QRect(80, 90, 240, 30))
        self.StartTime_Search.setMinimumSize(QtCore.QSize(240, 30))
        self.StartTime_Search.setMaximumSize(QtCore.QSize(240, 30))
        self.StartTime_Search.setStyleSheet("QLineEdit {\n"
                                            "    border: 2px solid rgb(37,39,48);\n"
                                            "    border-radius: 50px;\n"
                                            "    color: #FFF;\n"
                                            "    padding-left: 20px;\n"
                                            "    padding-right: 20px;\n"
                                            "}")
        self.StartTime_Search.setObjectName("StartTime_Search")
        self.EndTime_Search = QtWidgets.QLineEdit(parent=self.frame)
        self.EndTime_Search.setGeometry(QtCore.QRect(330, 90, 240, 30))
        self.EndTime_Search.setMinimumSize(QtCore.QSize(240, 30))
        self.EndTime_Search.setMaximumSize(QtCore.QSize(240, 30))
        self.EndTime_Search.setStyleSheet("QLineEdit {\n"
                                          "    border: 2px solid rgb(37,39,48);\n"
                                          "    border-radius: 50px;\n"
                                          "    color: #FFF;\n"
                                          "    padding-left: 20px;\n"
                                          "    padding-right: 20px;\n"
                                          "}")
        self.EndTime_Search.setObjectName("EndTime_Search")
        self.Search_Search = QtWidgets.QPushButton(parent=self.frame)
        self.Search_Search.setGeometry(QtCore.QRect(260, 130, 113, 32))
        self.Search_Search.setStyleSheet("QPushButton {\n"
                                         "    color: rgb(255, 255, 255);\n"
                                         "    background-color: rgb(35, 38, 53);\n"
                                         "    border: 0px solid;\n"
                                         "}\n"
                                         "QPushButton:hover {\n"
                                         "    background-color: rgb(49, 54, 80);\n"
                                         "}\n"
                                         "\n"
                                         "QPushButton:checked {\n"
                                         "    background-color: rgb(49, 54, 80);\n"
                                         "}")
        self.Search_Search.setObjectName("Search_Search")
        self.Result_List_Search = QtWidgets.QListWidget(parent=self.frame)
        self.Result_List_Search.setGeometry(QtCore.QRect(35, 200, 591, 291))
        self.Result_List_Search.setStyleSheet("background-color:  rgb(35, 38, 53);\n"
                                              "color:#FFF;")
        self.Result_List_Search.setObjectName("Result_List_Search")
        self.verticalLayout_6.addWidget(self.frame)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_2 = QtWidgets.QFrame(parent=self.page_3)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.StartTime_Anazye = QtWidgets.QLineEdit(parent=self.frame_2)
        self.StartTime_Anazye.setGeometry(QtCore.QRect(80, 90, 240, 30))
        self.StartTime_Anazye.setMinimumSize(QtCore.QSize(240, 30))
        self.StartTime_Anazye.setMaximumSize(QtCore.QSize(240, 30))
        self.StartTime_Anazye.setStyleSheet("QLineEdit {\n"
                                            "    border: 2px solid rgb(37,39,48);\n"
                                            "    border-radius: 50px;\n"
                                            "    color: #FFF;\n"
                                            "    padding-left: 20px;\n"
                                            "    padding-right: 20px;\n"
                                            "}")
        self.StartTime_Anazye.setObjectName("StartTime_Anazye")
        self.Location_Anazye = QtWidgets.QLineEdit(parent=self.frame_2)
        self.Location_Anazye.setGeometry(QtCore.QRect(80, 50, 240, 30))
        self.Location_Anazye.setMinimumSize(QtCore.QSize(240, 30))
        self.Location_Anazye.setMaximumSize(QtCore.QSize(240, 30))
        self.Location_Anazye.setStyleSheet("QLineEdit {\n"
                                           "    border: 2px solid rgb(37,39,48);\n"
                                           "    border-radius: 50px;\n"
                                           "    color: #FFF;\n"
                                           "    padding-left: 20px;\n"
                                           "    padding-right: 20px;\n"
                                           "}")
        self.Location_Anazye.setObjectName("Location_Anazye")
        self.EndTime_Anazye = QtWidgets.QLineEdit(parent=self.frame_2)
        self.EndTime_Anazye.setGeometry(QtCore.QRect(330, 90, 240, 30))
        self.EndTime_Anazye.setMinimumSize(QtCore.QSize(240, 30))
        self.EndTime_Anazye.setMaximumSize(QtCore.QSize(240, 30))
        self.EndTime_Anazye.setStyleSheet("QLineEdit {\n"
                                          "    border: 2px solid rgb(37,39,48);\n"
                                          "    border-radius: 50px;\n"
                                          "    color: #FFF;\n"
                                          "    padding-left: 20px;\n"
                                          "    padding-right: 20px;\n"
                                          "}")
        self.EndTime_Anazye.setObjectName("EndTime_Anazye")
        self.Text_Anazye = QtWidgets.QLineEdit(parent=self.frame_2)
        self.Text_Anazye.setGeometry(QtCore.QRect(330, 50, 240, 30))
        self.Text_Anazye.setMinimumSize(QtCore.QSize(240, 30))
        self.Text_Anazye.setMaximumSize(QtCore.QSize(240, 30))
        self.Text_Anazye.setStyleSheet("QLineEdit {\n"
                                       "    border: 2px solid rgb(37,39,48);\n"
                                       "    border-radius: 50px;\n"
                                       "    color: #FFF;\n"
                                       "    padding-left: 20px;\n"
                                       "    padding-right: 20px;\n"
                                       "}")
        self.Text_Anazye.setObjectName("Text_Anazye")
        self.Author_Anazye = QtWidgets.QLineEdit(parent=self.frame_2)
        self.Author_Anazye.setGeometry(QtCore.QRect(330, 10, 240, 30))
        self.Author_Anazye.setMinimumSize(QtCore.QSize(240, 30))
        self.Author_Anazye.setMaximumSize(QtCore.QSize(240, 30))
        self.Author_Anazye.setStyleSheet("QLineEdit {\n"
                                         "    border: 2px solid rgb(37,39,48);\n"
                                         "    border-radius: 50px;\n"
                                         "    color: #FFF;\n"
                                         "    padding-left: 20px;\n"
                                         "    padding-right: 20px;\n"
                                         "}")
        self.Author_Anazye.setObjectName("Author_Anazye")
        self.Search_Analyze = QtWidgets.QPushButton(parent=self.frame_2)
        self.Search_Analyze.setGeometry(QtCore.QRect(200, 130, 113, 32))
        self.Search_Analyze.setStyleSheet("QPushButton {\n"
                                          "    color: rgb(255, 255, 255);\n"
                                          "    background-color: rgb(35, 38, 53);\n"
                                          "    border: 0px solid;\n"
                                          "}\n"
                                          "QPushButton:hover {\n"
                                          "    background-color: rgb(49, 54, 80);\n"
                                          "}\n"
                                          "\n"
                                          "QPushButton:checked {\n"
                                          "    background-color: rgb(49, 54, 80);\n"
                                          "}")
        self.Search_Analyze.setObjectName("Search_Analyze")
        self.Hashtag_Anazye = QtWidgets.QLineEdit(parent=self.frame_2)
        self.Hashtag_Anazye.setGeometry(QtCore.QRect(80, 10, 240, 30))
        self.Hashtag_Anazye.setMinimumSize(QtCore.QSize(240, 30))
        self.Hashtag_Anazye.setMaximumSize(QtCore.QSize(240, 30))
        self.Hashtag_Anazye.setStyleSheet("QLineEdit {\n"
                                          "    border: 2px solid rgb(37,39,48);\n"
                                          "    border-radius: 50px;\n"
                                          "    color: #FFF;\n"
                                          "    padding-left: 20px;\n"
                                          "    padding-right: 20px;\n"
                                          "}")
        self.Hashtag_Anazye.setObjectName("Hashtag_Anazye")
        self.List_Analyze = QtWidgets.QListWidget(parent=self.frame_2)
        self.List_Analyze.setGeometry(QtCore.QRect(35, 200, 181, 291))
        self.List_Analyze.setStyleSheet("background-color:  rgb(35, 38, 53);\n"
                                        "color:#FFF;")
        self.List_Analyze.setObjectName("List_Analyze")
        self.TopTrend_Anazye = QtWidgets.QPushButton(parent=self.frame_2)
        self.TopTrend_Anazye.setGeometry(QtCore.QRect(340, 130, 113, 32))
        self.TopTrend_Anazye.setStyleSheet("QPushButton {\n"
                                           "    color: rgb(255, 255, 255);\n"
                                           "    background-color: rgb(35, 38, 53);\n"
                                           "    border: 0px solid;\n"
                                           "}\n"
                                           "QPushButton:hover {\n"
                                           "    background-color: rgb(49, 54, 80);\n"
                                           "}\n"
                                           "\n"
                                           "QPushButton:checked {\n"
                                           "    background-color: rgb(49, 54, 80);\n"
                                           "}")
        self.TopTrend_Anazye.setObjectName("TopTrend_Anazye")
        self.verticalLayout_8.addWidget(self.frame_2)
        self.stackedWidget.addWidget(self.page_3)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.horizontalLayout_2.addWidget(self.frame_pages)
        self.verticalLayout.addWidget(self.Content)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Title.setText(_translate("MainWindow", "Twitter Keeper"))
        self.Home_Page.setText(_translate("MainWindow", "Home"))
        self.Search_Page.setText(_translate("MainWindow", "Search"))
        self.Analyze_Page.setText(_translate("MainWindow", "Analyze"))
        self.PullTweet_Field.setText(_translate("MainWindow", "Pull Tweets"))
        self.Keyword_Pull_Field.setPlaceholderText(
            _translate("MainWindow", "Keyword"))
        self.Keyword_Pull_Field_2.setPlaceholderText(
            _translate("MainWindow", "Amount"))
        self.Hashtag_Search.setPlaceholderText(
            _translate("MainWindow", "Hashtag"))
        self.Author_Search.setPlaceholderText(
            _translate("MainWindow", "Author"))
        self.Location_Search.setPlaceholderText(
            _translate("MainWindow", "Location"))
        self.Text_Search.setPlaceholderText(_translate("MainWindow", "Text"))
        self.StartTime_Search.setPlaceholderText(
            _translate("MainWindow", "Start Time"))
        self.EndTime_Search.setPlaceholderText(
            _translate("MainWindow", "End Time"))
        self.Search_Search.setText(_translate("MainWindow", "Search"))
        self.StartTime_Anazye.setPlaceholderText(
            _translate("MainWindow", "Start Time"))
        self.Location_Anazye.setPlaceholderText(
            _translate("MainWindow", "Location"))
        self.EndTime_Anazye.setPlaceholderText(
            _translate("MainWindow", "End Time"))
        self.Text_Anazye.setPlaceholderText(_translate("MainWindow", "Text"))
        self.Author_Anazye.setPlaceholderText(
            _translate("MainWindow", "Author"))
        self.Search_Analyze.setText(_translate("MainWindow", "Search"))
        self.Hashtag_Anazye.setPlaceholderText(
            _translate("MainWindow", "Hashtag"))
        self.TopTrend_Anazye.setText(_translate("MainWindow", "Top Trend"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    # PAGE 1
    ui.Home_Page.clicked.connect(
        lambda: ui.stackedWidget.setCurrentWidget(ui.page_1))

    # PAGE 2
    ui.Search_Page.clicked.connect(
        lambda: ui.stackedWidget.setCurrentWidget(ui.page_2))

    # PAGE 3
    ui.Analyze_Page.clicked.connect(
        lambda: ui.stackedWidget.setCurrentWidget(ui.page_3))
    MainWindow.show()
    sys.exit(app.exec())
